# Generated by Django 4.1 on 2022-08-06 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='uniqie_id',
            new_name='unique_id',
        ),
    ]
