import http.client

conn = http.client.HTTPSConnection("api-test.bankrespublika.az")

headers = {
    'access_token': "eyJraWQiOiJkZWZhdWx0IiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJlNzAzYzE2NC00ZTI1LTQ5ZTAtODNjMS02NDRlMjVkOWUwOGEiLCJhdWQiOiJmM2NlMWNlMC1lNjcwLTQ3ZGQtOGUxYy1lMGU2NzAzN2RkNTQiLCJkb21haW4iOiI3NTMxODQ4Zi0yYTE0LTQ5NjItYjE4NC04ZjJhMTQ2OTYyYzAiLCJpc3MiOiJodHRwOlwvXC9hdXRoLXRlc3QuYmFua3Jlc3B1Ymxpa2EuYXpcL2FtXC9iYW5rcmVzcHVibGlrYVwvb2lkYyIsImV4cCI6MTY1OTg3NDc5NywiaWF0IjoxNjU5ODY3NTk3LCJqdGkiOiIxTTRaMXI0OEJBallPNmxwTXQ0VjB1LTBPci1GRldXLWNTTnM1UnFVV3ZzIn0.V8XpcjlxmhEjvRpl5_bqrMvWior238aJi1PGm1LyCGsjDVMC935qZWk1tCtTpM9QlIQqKRqPIfabRL2cjjIgY4siKt3cP9mCZ-SpRIG-xf8dfjt7iUyGxTJWrYNQ09LzWY-kZjHTGsPXmWN9iDm2A23UufdesMOQ181XHXBBHMlo6CJWMeMeiKe5kbATIReFsgs5Pow01KEVuYxyDV_kSkWRP6JSRgdnY3GQa6Zf1XCGcavwZVQvgglo4ReJ74HIM5aeeNIIxbtLsLbF-I964GyAlxeb3PX3MewegSFrdIw0o_9NkHIfYN0sxavlzJy7eQBaPWuLkda5V3yu25DlAQ",
    'accept': "application/json"
    }

conn.request("GET", "/open-banking/aisp/v2/accounts", headers=headers)

res = conn.getresponse()
data = res.read()

print(data.decode("utf-8"))
